# Generated by Django 3.1.1 on 2020-10-13 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_release_name', models.CharField(default='Non Specified', max_length=100)),
                ('last_release_date', models.DateTimeField(default=datetime.date.today)),
                ('spotify_link', models.CharField(default='Non Specified', max_length=200)),
                ('genres', models.ManyToManyField(blank=True, related_name='artists', to='api.Genre')),
            ],
        ),
    ]
