# Generated by Django 3.1.1 on 2020-10-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201015_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotidyAuth',
            new_name='SpotifyAuth',
        ),
    ]
