# Generated by Django 3.1.1 on 2020-10-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201015_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyAuth',
        ),
    ]
