# Generated by Django 3.1.1 on 2020-10-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyAuth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyauth',
            old_name='refresh_roken',
            new_name='refresh_token',
        ),
    ]
